### ISSUE TITLE
Could the same results for be produces for Malayalam language?

### ISSUE THREAD

**Issue by guyandtheworld** [AshokR/TamilNLP#4]
Hi! This is a project I'm doing, I know porting this from Tamil would be easy due to the similarity between the languages but could you give me a few insights on how to proceed?

**Comment by AshokR** [comment]
Hi Adarsh, I am happy to know that you are working on a Malayalam NLP project. I will be happy to help you. As you said, porting should be easy because of the similarity of languages. You might want to start by collecting a Malayalam corpus. You can modify my Wiki By Category script to create a corpus from Malayalam Wikipedia site. Change the locale, point at the Malayalam Wikipedia site and name a Malayalam Wikipedia category for example. Post a message if you run into a specific problem. Best of luck!

**Comment by guyandtheworld** [comment]
I'm doing a talk on this exact topic that is Implications of NLP on regional languages during FOSSASIA Summit 2018 at Singapore. I was planning on doing on how I made POS tagger for Malayalam and try too increase the awareness of the lack of Open Source and technology within the non-english language community. Since you have this much experience in this field, would you like to go through my talk proposal and give me advice on what all changes should be made to my talk or what all additional things I could add to make my talk the most meaningful in the given time? (I'm a rookie in NLP) Any ideas, problems or any difficulties you are aware in this field are most welcome! :smile: 

This is the event https://2018.fossasia.org/

Do let me know what you think.

**Comment by AshokR** [comment]
I dabble in NLP when I get some free time. I do not know Malayalam either. However, I will be happy to go through your talk proposal and give you what feedback I can.

**Comment by guyandtheworld** [comment]
@AshokR Can I E-mail you the abstract? :smile:

**Comment by guyandtheworld** [comment]
@AshokR The topic is not specific to Malayalam but it's on NLP on regional languages, so your insights will be very valuable.

**Comment by AshokR** [comment]
My ______ is my ______ followed by ______.

**Comment by guyandtheworld** [comment]
Okay, thank you so much! I'll close this issue now.
